databases:
  -name: Khakis
  user: khakis
  plane: free
  region: oregon


services:
  -type: web
  name: Khakis
  region: oregon
  branch: main
  env: ruby
  buildCommand: "./bin/render-build.sh"
  startCommand: "rails s"
  envVars:
    -key: DATABASE_URL
      fromDatabase:
        name: Khakis
        property: connectionString
    -key: RAILS_MASTER_KEY
      sync: false